Repository open-component-model/ocm, pull requests merged in 2023-11, with the labels that each got.

#565 feat: add pre-flight check for installing ocm-controller
  .golangci.yaml
  cmds/ocm/commands/controllercmds/install/cmd.go
  cmds/ocm/commands/controllercmds/install/cmd_test.go
  cmds/ocm/commands/controllercmds/install/install_cert_manager.go
  cmds/ocm/commands/controllercmds/install/issuer/registry_certificate.yaml
Labels: size/m

#574 Update Goreleaser cosign handling
  .goreleaser.yaml
Labels: size/xs

#581 Update dependabot.yml
  .github/dependabot.yml
Labels: size/s

#586 Add Reports to Mend Scans
  .github/workflows/mend.config
  .github/workflows/mend_scan.yaml
Labels: size/m

#593 Skip Report generation on scheduled run + non PR runs
  .github/workflows/mend_scan.yaml
Labels: size/xs
