Repository open-component-model/ocm, pull requests merged in 2023-10, with the labels that each got.

#538 add dependabot.yml
  .github/dependabot.yml
Labels: size/s

#543 add detect version
  .github/workflows/blackduck_scan.yaml
  .github/workflows/blackduck_scan_scheduled.yaml
Labels: size/xs

#547 Blackduck detect version
  .github/workflows/blackduck_scan.yaml
  .github/workflows/pr_run_inttest.yaml
Labels: size/xs

#548 Blackduck detect version
  .github/workflows/blackduck_scan.yaml
Labels: size/xs

#549 Blackduck detect version
  .github/workflows/blackduck_scan.yaml
Labels: size/s

#551 remove
  .github/workflows/blackduck_scan.yaml
Labels: size/m

#555 adopt to go-version-file
  .github/workflows/components.yaml
  .github/workflows/lint_and_test.yaml
Labels: size/s
