Repository open-component-model/ocm, pull requests merged in 2024-10, with the labels that each got.

#943 Add a simpler digest verify function
  api/ocm/compdesc/meta/v1/identity.go
  api/ocm/tools/signing/digest.go
Labels: area/ipcei

#942 [chore]: Install wingetcreate
  .github/workflows/publish.yaml
Labels: size/xs, fix

#948 [chore]: release-notes-url isn't supported by wingetcreate v1.6.1.0
  .github/workflows/publish.yaml
Labels: size/xs, fix

#950 fix: docker registry returning internal server error on blobs not found
  api/oci/extensions/repositories/ocireg/namespace.go
  api/oci/extensions/repositories/ocireg/utils.go
Labels: size/s

#955 feat: add function to satisfy accessMethodView interface
  api/ocm/tools/signing/digest.go
Labels: area/ipcei

#959 chore(deps): bump the go group across 1 directory with 11 updates - recreation of #956
  .github/config/wordlist.txt
  api/utils/dirtree/tar.go
  api/utils/dirtree/utils.go
  api/utils/tarutils/extract.go
  docs/releasenotes/v0.16.0.md
  examples/lib/tour/01-getting-started/README.md
  flake.nix
  go.mod
  go.sum
  hack/Makefile
Labels: size/l, dependencies

#974 fix: GHA - .github/workflows/flake_vendorhash.yaml
  .github/workflows/flake_vendorhash.yaml
Labels: size/s, github_actions, chore

#975 fix: ignore ORA error instead of containerd error
  api/ocm/extensions/pubsub/providers/ocireg/provider.go
Labels: area/ipcei, fix

#968 fix: wrap the TLS config into a retryer client
  api/oci/extensions/repositories/ocireg/namespace.go
  api/oci/extensions/repositories/ocireg/repository.go
Labels: size/s

#973 fix closure + digest mode + ctf index
  api/oci/extensions/repositories/ctf/index/index.go
  api/oci/extensions/repositories/ctf/index/index_test.go
  api/ocm/tools/signing/options.go
  cmds/ocm/commands/ocmcmds/cli/download/cmd.go
  cmds/ocm/commands/ocmcmds/common/handlers/comphdlr/closure.go
  cmds/ocm/commands/ocmcmds/common/handlers/comphdlr/util.go
  cmds/ocm/commands/ocmcmds/components/get/cmd.go
  cmds/ocm/commands/ocmcmds/components/hash/cmd.go
  cmds/ocm/commands/ocmcmds/components/hash/cmd_test.go
  cmds/ocm/commands/ocmcmds/references/get/cmd.go
  cmds/ocm/commands/ocmcmds/resources/download/cmd.go
  cmds/ocm/commands/ocmcmds/resources/get/cmd.go
  cmds/ocm/commands/ocmcmds/sources/get/cmd.go
  cmds/ocm/common/output/options.go
Labels: fix

#978 fix: setting up the github name and email
  .github/workflows/release-branch.yaml
Labels: size/xs, fix

#980 fix: use a permission token for pushing a new tag
  .github/workflows/release-branch.yaml
Labels: size/xs

#981 fix: using the bot token to check out the repository
  .github/workflows/release-branch.yaml
Labels: size/s, fix

#983 fix: wrap the TLS config into a retryer client (#968)
  api/oci/extensions/repositories/ocireg/namespace.go
  api/oci/extensions/repositories/ocireg/repository.go
Labels: size/s

#979 documentation: Update the installation options
  .github/config/wordlist.txt
  README.md
Labels: area/documentation, size/s, documentation

#991 documentation: fix uploader documentation
  api/ocm/extensions/blobhandler/config/type.go
  docs/reference/ocm_configfile.md
Labels: area/documentation, size/s, component/ocm-cli, documentation

#1001 Fix/publish release
  .github/workflows/publish.yaml
  hack/chocolatey/update.ps1
Labels: size/xs, fix

#1004 chore(ci): make sure we use candidates and branches by default
  .github/workflows/release.yaml
  RELEASE_PROCESS.md
Labels: chore

#1002 chore(ci): add stale bot for issues
  .github/workflows/stale.yaml
Labels: chore

#1008 chore(ci): use reusable stale bot configuration
  .github/workflows/stale.yaml
Labels: chore

#1006 fix!(release): retract 0.16.0-z
  go.mod
Labels: fix

#992 chore(release): also call make generate to update files
  .github/workflows/release.yaml
Labels: chore

#1005 Revert "feat: replace docker with oras (#904)"
  api/oci/extensions/repositories/ocireg/blobs.go
  api/oci/extensions/repositories/ocireg/namespace.go
  api/oci/extensions/repositories/ocireg/repository.go
  api/oci/extensions/repositories/ocireg/utils.go
  api/ocm/extensions/pubsub/providers/ocireg/provider.go
  api/tech/docker/README.md
  api/tech/docker/errors/errors.go
  api/tech/docker/fetcher.go
  api/tech/docker/handler.go
  api/tech/docker/httpreadseeker.go
  api/tech/docker/lister.go
  api/tech/docker/orig.go
  api/tech/docker/pusher.go
  api/tech/docker/registry.go
  api/tech/docker/resolve/interface.go
  api/tech/docker/resolver.go
  go.mod
  go.sum
Labels: size/l, area/ipcei

#1013 fix: correct the default URL for uninstalling ocm controller
  api/ocm/extensions/repositories/genericocireg/annotation_test.go
  cmds/ocm/commands/controllercmds/uninstall/cmd.go
  cmds/ocm/commands/ocmcmds/components/hash/cmd_test.go
  docs/reference/ocm_controller_uninstall.md
  docs/releasenotes/v0.17.0-rc.1.md
  examples/lib/tour/01-getting-started/README.md
Labels: size/s, fix

#1015 fix double completion of option sets in CLI
  api/ocm/extensions/attrs/ociuploadattr/attr.go
  cmds/ocm/commands/ocmcmds/common/utils.go
  cmds/ocm/common/options/interfaces.go
Labels: area/performance

#1023 chore: release fallout corrections
  .github/workflows/release.yaml
  examples/lib/tour/01-getting-started/README.md
Labels: github_actions, chore :hammer:, fix, chore

#1024 fix: remove ocm release key if present
  .github/workflows/release.yaml
Labels: github_actions, chore :hammer:, fix, chore
