Repository open-component-model/ocm, pull requests merged in 2024-03, with the labels that each got.

#682 remove second trigger and just keep pull_request_target
  .github/workflows/codecov.yaml
  .github/workflows/mend_scan.yaml
Labels: size/s

#684 MIT LICENSE for npm publish gist
  .reuse/dep5
  LICENSES/MIT.txt
  pkg/contexts/ocm/blobhandler/handlers/generic/npm/blobhandler.go
  pkg/contexts/ocm/blobhandler/handlers/generic/npm/publish.go
Labels: size/m

#692 use app token in release
  .github/workflows/release.yaml
Labels: size/xs

#698 support for github enterprise urls
  pkg/contexts/credentials/builtin/github/identity/identity.go
Labels: size/xs

#699 follow Docker official images recommendation
  .dockerignore
  .github/workflows/push_ocm.yaml
  Dockerfile
  README.md
  components/ocmcli/Dockerfile
  components/ocmcli/README.md
  components/ocmcli/ocm.sh
Labels: size/m

#704 let's add a `user` within Docker
  Dockerfile
  cmds/ocm/topics/ocm/labels/topic.go
  components/ocmcli/Dockerfile
  examples/lib/tour/01-getting-started/README.md
Labels: component/ocm-cli

#705 Fix repository cache
  cmds/ocm/commands/ocmcmds/components/check/cmd.go
  cmds/ocm/commands/ocmcmds/components/check/options.go
  pkg/contexts/ocm/internal/resolver.go
  pkg/contexts/ocm/session.go
Labels: size/s, component/ocm-core
