Repository open-component-model/ocm, pull requests merged in 2024-02, with the labels that each got.

#650 Fix/npm publish
  pkg/contexts/ocm/blobhandler/handlers/generic/npm/publish.go
  pkg/contexts/ocm/blobhandler/handlers/generic/npm/publish_test.go
  pkg/contexts/ocm/blobhandler/handlers/generic/npm/suite_test.go
  pkg/contexts/ocm/blobhandler/handlers/generic/npm/testdata/testdata.tgz
Labels: size/s

#654 add epic
  .github/ISSUE_TEMPLATE/epic.md
Labels: size/xs

#667 let's run only, where we have API key available
  .github/workflows/mend_scan.yaml
Labels: size/xs

#653 Npm/config
  docs/reference/ocm.md
  docs/reference/ocm_credential-handling.md
  docs/reference/ocm_get_credentials.md
  docs/reference/ocm_logging.md
  docs/reference/ocm_ocm-uploadhandlers.md
  docs/reference/ocm_transfer_commontransportarchive.md
  docs/reference/ocm_transfer_componentversions.md
  pkg/contexts/config/configutils/configure.go
  pkg/contexts/credentials/builtin/npm/identity/identity.go
  pkg/contexts/credentials/repositories/dockerconfig/type.go
  pkg/contexts/credentials/repositories/gardenerconfig/type.go
  pkg/contexts/credentials/repositories/init.go
  pkg/contexts/credentials/repositories/npm/a_usage.go
  pkg/contexts/credentials/repositories/npm/cache.go
  pkg/contexts/credentials/repositories/npm/config.go
  pkg/contexts/credentials/repositories/npm/config_test.go
  pkg/contexts/credentials/repositories/npm/default.go
  pkg/contexts/credentials/repositories/npm/provider.go
  pkg/contexts/credentials/repositories/npm/repository.go
  pkg/contexts/credentials/repositories/npm/repository_test.go
  pkg/contexts/credentials/repositories/npm/suite_test.go
  pkg/contexts/credentials/repositories/npm/testdata/.npmrc
  pkg/contexts/credentials/repositories/npm/type.go
  pkg/contexts/ocm/attrs/plugindirattr/attr.go
  pkg/contexts/ocm/blobhandler/handlers/generic/npm/blobhandler.go
  pkg/contexts/ocm/blobhandler/handlers/generic/npm/const.go
  pkg/contexts/ocm/blobhandler/handlers/generic/npm/registration_test.go
  pkg/contexts/ocm/utils/configure.go
  pkg/contexts/ocm/utils/defaultconfigregistry/configure.go
  pkg/utils/path.go
Labels: size/l

#669 parse and validate some input parameters as filesystem-paths
  cmds/ocm/commands/ocmcmds/common/inputs/options/standard.go
  cmds/ocm/commands/ocmcmds/common/inputs/utils.go
  go.mod
  go.sum
  pkg/cobrautils/flag/path.go
  pkg/cobrautils/flag/path_array.go
  pkg/cobrautils/flag/path_array_test.go
  pkg/cobrautils/flag/path_array_win_test.go
  pkg/cobrautils/flag/path_test.go
  pkg/cobrautils/flag/path_win_test.go
  pkg/cobrautils/flag/replace.go
  pkg/cobrautils/flagsets/types.go
Labels: size/m
