Repository open-component-model/ocm, pull requests merged in 2024-05, with the labels that each got.

#759 add negative test for non-semver version
  pkg/contexts/ocm/repositories/genericocireg/repo_test.go
Labels: size/s

#760 add cleanup to action for self hosted runner
  .github/workflows/buildcomponents.yaml
  .github/workflows/components.yaml
  .github/workflows/lint_and_test.yaml
  .github/workflows/release.yaml
Labels: size/s

#734 Fix ocm issue 179, block in config yields invalid yaml
  go.mod
  go.sum
  pkg/contexts/ocm/utils/localize/instantiate_test.go
  pkg/contexts/ocm/utils/localize/subst.go
  pkg/contexts/ocm/utils/localize/subst_test.go
  pkg/contexts/ocm/utils/localize/target_test.go
  pkg/contexts/ocm/utils/localize/utils_test.go
  pkg/utils/subst/subst.go
  pkg/utils/subst/subst_test.go
Labels: component/ocm-cli, component/ocm-core

#757 Npm/auth access
  pkg/contexts/ocm/accessmethods/npm/method.go
  pkg/contexts/ocm/blobhandler/handlers/generic/npm/blobhandler.go
  pkg/contexts/ocm/blobhandler/handlers/generic/npm/publish.go
  pkg/npm/login.go
Labels: size/m

#764 Create codeql.yml
  .github/workflows/codeql.yml
Labels: size/s

#745 fix: stop ignoring most of the errors
  cmds/demoplugin/accessmethods/demo.go
  cmds/demoplugin/uploaders/demo.go
  cmds/ocm/commands/misccmds/rsakeypair/cmd.go
  cmds/ocm/commands/ocicmds/common/handlers/artifacthdlr/attached.go
  cmds/ocm/commands/ocicmds/common/handlers/artifacthdlr/clean.go
  cmds/ocm/commands/ocicmds/common/handlers/artifacthdlr/closure.go
  cmds/ocm/commands/ocicmds/common/handlers/artifacthdlr/typehandler.go
  cmds/ocm/commands/ocmcmds/common/addconfig.go
  cmds/ocm/commands/ocmcmds/common/handlers/comphdlr/typehandler.go
  cmds/ocm/commands/ocmcmds/common/handlers/vershdlr/typehandler.go
  cmds/ocm/commands/ocmcmds/common/options/fileoption/option.go
  cmds/ocm/commands/ocmcmds/plugins/describe/describe.go
  cmds/ocm/commands/toicmds/package/bootstrap/cmd.go
  cmds/ocm/topics/common/attributes/topic.go
  pkg/contexts/oci/artdesc/artifact.go
  pkg/contexts/ocm/accessmethods/npm/method.go
  pkg/contexts/ocm/attrs/ociuploadattr/attr.go
  pkg/contexts/ocm/attrs/plugindirattr/attr.go
  pkg/contexts/ocm/plugin/cache/plugindir.go
  pkg/contexts/ocm/plugin/cache/updater.go
  pkg/contexts/ocm/repositories/comparch/componentarchive.go
  pkg/contexts/ocm/repositories/comparch/repository.go
  pkg/contexts/ocm/repositories/genericocireg/componentversion.go
  pkg/mimeutils/type.go
  pkg/toi/support/support.go
Labels: size/m

#767 feat: add silent flag and fix dry run with prerequisites
  cmds/ocm/commands/controllercmds/common/manifests.go
  cmds/ocm/commands/controllercmds/install/cmd.go
  cmds/ocm/commands/controllercmds/install/install_cert_manager.go
  cmds/ocm/commands/controllercmds/uninstall/cmd.go
Labels: size/s

#731 Maven/access2
  .reuse/dep5
  LICENSES/BSD-3-Clause.txt
  docs/pluginreference/plugin_accessmethod_compose.md
  docs/pluginreference/plugin_descriptor.md
  docs/pluginreference/plugin_valueset_compose.md
  docs/reference/ocm_add_resource-configuration.md
  docs/reference/ocm_add_resources.md
  docs/reference/ocm_add_source-configuration.md
  docs/reference/ocm_add_sources.md
  docs/reference/ocm_controller_install.md
  docs/reference/ocm_controller_uninstall.md
  docs/reference/ocm_credential-handling.md
  docs/reference/ocm_get_credentials.md
  docs/reference/ocm_logging.md
  docs/reference/ocm_ocm-accessmethods.md
  docs/reference/ocm_ocm-uploadhandlers.md
  docs/reference/ocm_transfer_commontransportarchive.md
  docs/reference/ocm_transfer_componentversions.md
  hack/Makefile
  hack/tools.go
  pkg/blobaccess/wget/access.go
  pkg/cobrautils/flag/path_array_test.go
  pkg/cobrautils/flag/path_array_win_test.go
  pkg/cobrautils/flag/path_test.go
  pkg/cobrautils/flag/path_win_test.go
  pkg/contexts/credentials/builtin/mvn/identity/identity.go
  pkg/contexts/credentials/builtin/npm/identity/identity.go
  pkg/contexts/ocm/accessmethods/init.go
  pkg/contexts/ocm/accessmethods/mvn/README.md
  pkg/contexts/ocm/accessmethods/mvn/cli.go
  pkg/contexts/ocm/accessmethods/mvn/coordinates.go
  pkg/contexts/ocm/accessmethods/mvn/coordinates_test.go
  pkg/contexts/ocm/accessmethods/mvn/integration_test.go
  pkg/contexts/ocm/accessmethods/mvn/method.go
  pkg/contexts/ocm/accessmethods/mvn/method_test.go
  pkg/contexts/ocm/accessmethods/mvn/suite_test.go
  pkg/contexts/ocm/accessmethods/mvn/testdata/.m2/repository/com/sap/cloud/sdk/sdk-modules-bom/5.7.0/sdk-modules-bom-5.7.0.pom
  pkg/contexts/ocm/accessmethods/mvn/testdata/.m2/repository/com/sap/cloud/sdk/sdk-modules-bom/5.7.0/sdk-modules-bom-5.7.0.pom.sha1
  pkg/contexts/ocm/accessmethods/mvn/testdata/fail/test/repository/42/repository-42.pom
  pkg/contexts/ocm/accessmethods/mvn/testdata/fail/test/repository/42/repository-42.pom.sha1
  pkg/contexts/ocm/accessmethods/options/standard.go
  pkg/contexts/ocm/blobhandler/handlers/generic/mvn/blobhandler.go
  pkg/contexts/ocm/blobhandler/handlers/generic/mvn/blobhandler_test.go
  pkg/contexts/ocm/blobhandler/handlers/generic/mvn/registration.go
  pkg/contexts/ocm/blobhandler/handlers/generic/mvn/registration_test.go
  pkg/contexts/ocm/blobhandler/handlers/generic/mvn/suite_test.go
  pkg/contexts/ocm/blobhandler/handlers/init.go
  pkg/contexts/ocm/elements/artifactaccess/mvnaccess/resource.go
  pkg/contexts/ocm/internal/blobhandler.go
  pkg/contexts/ocm/resourcetypes/const.go
  pkg/iotools/hashReaderWriter.go
  pkg/iotools/hashReaderWriter_test.go
  pkg/iotools/suite_test.go
  pkg/mime/types.go
  pkg/mimeutils/type.go
  pkg/utils/tarutils/extract.go
  pkg/utils/tarutils/pack.go
  pkg/utils/tarutils/pack_test.go
  pkg/version/generate/release_generate.go
  pkg/version/version.go
Labels: size/l

#772 fix: use sync.OnceFunc instead of the struct package local value
  pkg/utils/subst/subst.go
Labels: size/xs

#776 remove SPDX Header
  pkg/contexts/credentials/internal/logging.go
  pkg/contexts/credentials/repositories/vault/repo_int_test.go
  pkg/contexts/credentials/repositories/vault/repo_test.go
  pkg/errkind/kinds.go
  pkg/errkind/utils.go
  pkg/errors/doc.go
  pkg/exception/doc.go
  pkg/finalizer/doc.go
  pkg/generics/doc.go
  pkg/runtimefinalizer/object.go
  pkg/runtimefinalizer/object_test.go
  pkg/runtimefinalizer/suite_test.go
Labels: size/s

#779 early CD validation for AddVersion
  pkg/contexts/ocm/cpi/repocpi/bridge_c.go
  pkg/contexts/ocm/repositories/composition/repository_test.go
Labels: area/ipcei

#780 fix: only have yaml out put on stdout if dryrun is enabled
  cmds/ocm/commands/controllercmds/common/log.go
  cmds/ocm/commands/controllercmds/common/manifests.go
  cmds/ocm/commands/controllercmds/install/cmd.go
  cmds/ocm/commands/controllercmds/install/cmd_test.go
  cmds/ocm/commands/controllercmds/install/install_cert_manager.go
  cmds/ocm/commands/controllercmds/uninstall/cmd_test.go
Labels: size/s

#782 sonatype nexus - quirks modes
  docs/reference/ocm_credential-handling.md
  docs/reference/ocm_get_credentials.md
  pkg/contexts/credentials/builtin/npm/identity/identity.go
  pkg/contexts/credentials/repositories/npm/config_test.go
  pkg/contexts/credentials/repositories/npm/provider.go
  pkg/contexts/credentials/repositories/npm/repository.go
  pkg/contexts/ocm/accessmethods/npm/method.go
  pkg/contexts/ocm/accessmethods/npm/method_test.go
  pkg/contexts/ocm/blobhandler/handlers/generic/npm/blobhandler.go
  pkg/iotools/digests.go
  pkg/iotools/digests_test.go
  pkg/npm/login.go
  pkg/npm/structs.go
Labels: size/m
