Repository open-component-model/ocm, pull requests merged in 2024-08, with the labels that each got.

#860 Typo
  cmds/ocm/commands/toicmds/package/bootstrap/cmd.go
  docs/reference/ocm_add_resource-configuration.md
  docs/reference/ocm_add_resources.md
  docs/reference/ocm_add_source-configuration.md
  docs/reference/ocm_add_sources.md
  docs/reference/ocm_bootstrap_package.md
  docs/reference/ocm_ocm-pubsub.md
  docs/reference/ocm_set_pubsub.md
  go.mod
Labels: size/s

#861 feat: add check for diffs after go mod tidy and generate
  .github/workflows/check_diff_action.yaml
Labels: size/s

#876 fix cli docu generation
  api/utils/cobrautils/links.go
  cmds/ocm/commands/ocicmds/cmd.go
  cmds/ocm/commands/ocmcmds/cmd.go
  cmds/ocm/commands/toicmds/config/bootstrap/cmd.go
  cmds/ocm/common/utils/command.go
  cmds/ocm/topics/toi/bootstrapping/topic.go
  docs/reference/ocm_bootstrap_configuration.md
  docs/reference/ocm_bootstrap_configuration_toi-bootstrapping.md
  docs/reference/ocm_bootstrap_package.md
  docs/reference/ocm_bootstrap_package_toi-bootstrapping.md
  docs/reference/ocm_configfile.md
  docs/reference/ocm_describe_package_toi-bootstrapping.md
  docs/reference/ocm_oci.md
  docs/reference/ocm_ocm.md
  docs/reference/ocm_toi-bootstrapping.md
  hack/generate-docs/cobradoc/md_docs.go
Labels: area/ipcei

#867 introduce optional repository interface for resolvers
  api/ocm/cpi/dummy.go
  api/ocm/cpi/interface.go
  api/ocm/cpi/modopts.go
  api/ocm/cpi/repocpi/interface.go
  api/ocm/cpi/repocpi/view_cv.go
  api/ocm/cpi/utils.go
  api/ocm/extensions/repositories/composition/type.go
  api/ocm/extensions/repositories/virtual/type.go
  api/ocm/interface.go
  api/ocm/internal/repository.go
  api/ocm/internal/resolver.go
  api/ocm/resolver.go
  api/ocm/resolver_test.go
  api/ocm/types/interface.go
  cmds/ocm/commands/ocmcmds/common/handlers/vershdlr/suite_test.go
  cmds/ocm/commands/ocmcmds/common/handlers/vershdlr/typehandler.go
  cmds/ocm/commands/ocmcmds/common/handlers/vershdlr/typehandler_test.go
  cmds/ocm/commands/ocmcmds/common/options/lookupoption/option.go
Labels: area/ipcei

#873 ignore status error for reading pubsub config
  api/ocm/extensions/pubsub/providers/ocireg/provider.go
Labels: area/ipcei

#883 raise alpine version
  .github/workflows/push_ocm.yaml
  Dockerfile
  README.md
  api/oci/extensions/repositories/docker/client.go
  components/helminstaller/Dockerfile
  components/ocmcli/Dockerfile
Labels: size/s

#888 Add linux packages to goreleaser
  .github/workflows/release.yaml
  .goreleaser.yaml
Labels: size/s

#885 disable manual/secondary caching
  .github/workflows/release.yaml
  sonar-project.properties
Labels: size/s

#866 Validate method for oci/ocm repository specs
  api/oci/extensions/repositories/artifactset/format.go
  api/oci/extensions/repositories/artifactset/type.go
  api/oci/extensions/repositories/ctf/format.go
  api/oci/extensions/repositories/ctf/type.go
  api/oci/extensions/repositories/docker/docker_test.go
  api/oci/extensions/repositories/docker/suite_test.go
  api/oci/extensions/repositories/docker/type.go
  api/oci/extensions/repositories/empty/type.go
  api/oci/extensions/repositories/ocireg/type.go
  api/oci/internal/repotypes.go
  api/ocm/extensions/repositories/comparch/comparch_test.go
  api/ocm/extensions/repositories/comparch/format.go
  api/ocm/extensions/repositories/comparch/type.go
  api/ocm/extensions/repositories/composition/type.go
  api/ocm/extensions/repositories/genericocireg/type.go
  api/ocm/extensions/repositories/virtual/type.go
  api/ocm/internal/repotypes.go
  api/utils/accessio/opts.go
  api/utils/accessobj/accessobject.go
  api/utils/tcp/ping.go
Labels: area/ipcei

#886 feat: add npm input type
  api/ocm/extensions/accessmethods/npm/method_test.go
  api/ocm/extensions/accessmethods/options/standard.go
  cmds/ocm/commands/ocmcmds/common/inputs/options/standard.go
  cmds/ocm/commands/ocmcmds/common/inputs/types/npm/cli.go
  cmds/ocm/commands/ocmcmds/common/inputs/types/npm/input_test.go
  cmds/ocm/commands/ocmcmds/common/inputs/types/npm/spec.go
  cmds/ocm/commands/ocmcmds/common/inputs/types/npm/suite_test.go
  cmds/ocm/commands/ocmcmds/common/inputs/types/npm/type.go
  docs/pluginreference/plugin_accessmethod_compose.md
  docs/pluginreference/plugin_descriptor.md
  docs/pluginreference/plugin_valueset_compose.md
Labels: size/m

#889 move migrate tooling to 'hack' folder
  hack/migrate.md
  hack/migrate.mig
  hack/migrate.sh
Labels: size/xs

#893 chore: change release notes template, auto label PRs, ...
  .github/config/pr-labeler.yml
  .github/pull_request_template.md
  .github/release-drafter.yml
  .github/workflows/pr-labeler-kind.yaml
  .github/workflows/pr-labeler-size.yml
Labels: size/s, chore :hammer:

#894 chore: always create a new release branch and delete all old ones during new release action
  .github/config/goreleaser.yaml
  .github/pull_request_template.md
  .github/workflows/lint_and_test.yaml
  .github/workflows/release.yaml
Labels: size/s, chore :hammer:
