Repository open-component-model/ocm, pull requests merged in 2024-06, with the labels that each got.

#789 add workflow for updateVendorHash of flake
  .github/workflows/flake_vendorhash.yaml
  flake.nix
Labels: component/ocm-core

#791 fix update-vendor-hash
  .golangci.yaml
  flake.nix
Labels: size/s

#793 fix updateVendorHash
  .github/workflows/flake_vendorhash.yaml
Labels: size/xs

#795 sign flake.nix updates
  .github/workflows/flake_vendorhash.yaml
Labels: size/s

#800 finally at least be able to sign commits
  .github/workflows/flake_vendorhash.yaml
Labels: size/s

#806 Revert "Bump goreleaser/goreleaser-action from 5 to 6 in the ci group…
  .github/workflows/release.yaml
Labels: size/xs

#807 update release notes
  docs/releasenotes/v0.11.0.md
Labels: size/xs

#809 auto update `flake.nix` vendor hash incl. singed commit
  .github/workflows/flake_vendorhash.yaml
  flake.lock
Labels: size/s

#819 fix https://github.com/open-component-model/ocm-project/issues/196
  cmds/ocm/commands/ocmcmds/components/transfer/cmd.go
Labels: area/ipcei

#822 Update README.md
  README.md
Labels: area/documentation, size/xs

#826 enhance the auto update of the flake vendor hash
  .github/workflows/flake_vendorhash.yaml
Labels: size/s

#824 close() writer, before trying to rename
  .gitignore
  cmds/ocm/ca/component-descriptor.yaml
  cmds/ocm/ocm_test.go
  cmds/ocm/suite_test.go
  pkg/common/accessio/cache.go
Labels: size/s

#828 cleanup unused
  hack/Makefile
  hack/install-requirements.sh
Labels: size/s

#831 fix duplicate command argument for plugin command execution
  pkg/contexts/ocm/plugin/plugin.go
Labels: size/xs
