Repository open-component-model/ocm, pull requests merged in 2024-07, with the labels that each got.

#837 fix broken links
  README.md
Labels: size/xs

#848 forward error message from OCI registry
  pkg/docker/errors/errors.go
  pkg/docker/pusher.go
Labels: area/ipcei

#840 cleanup json schemes
  examples/lib/tour/01-getting-started/README.md
  pkg/contexts/ocm/compdesc/versions/ocm.software/v3alpha1/jsonscheme/bindata.go
  pkg/contexts/ocm/compdesc/versions/v2/jsonscheme/bindata.go
  resources/component-descriptor-ocm-v3-schema.yaml
  resources/component-descriptor-v2-schema.yaml
Labels: area/ipcei

#855 Add AUR as installation option for OCM-CLI
  README.md
Labels: size/s

#844 Rework adding elements to a component version
  cmds/ocm/commands/ocmcmds/common/addhdlrs/base.go
  cmds/ocm/commands/ocmcmds/common/addhdlrs/comp/elements.go
  cmds/ocm/commands/ocmcmds/common/addhdlrs/options.go
  cmds/ocm/commands/ocmcmds/common/addhdlrs/refs/elements.go
  cmds/ocm/commands/ocmcmds/common/addhdlrs/rscs/elements.go
  cmds/ocm/commands/ocmcmds/common/addhdlrs/srcs/elements.go
  cmds/ocm/commands/ocmcmds/components/add/cmd.go
  cmds/ocm/commands/ocmcmds/references/add/cmd.go
  cmds/ocm/commands/ocmcmds/references/add/cmd_test.go
  cmds/ocm/commands/ocmcmds/references/add/testdata/dupreferences.yaml
  cmds/ocm/commands/ocmcmds/resources/add/cmd.go
  cmds/ocm/commands/ocmcmds/resources/add/cmd_test.go
  cmds/ocm/commands/ocmcmds/resources/add/testdata/dupresources.yaml
  cmds/ocm/commands/ocmcmds/sourceconfig/add/cmd.go
  cmds/ocm/commands/ocmcmds/sources/add/cmd.go
  cmds/ocm/commands/ocmcmds/sources/add/cmd_test.go
  cmds/ocm/commands/ocmcmds/sources/add/testdata/dupsources.yaml
  docs/reference/ocm_add_componentversions.md
  docs/reference/ocm_add_references.md
  docs/reference/ocm_add_resources.md
  docs/reference/ocm_add_sources.md
  examples/lib/comparison-scenario/01-create.go
  examples/lib/tour/02-composing-a-component-version/01-basic-componentversion-creation.go
  examples/lib/tour/02-composing-a-component-version/README.md
  examples/lib/tour/03-working-with-credentials/common.go
  examples/lib/tour/05-transporting-component-versions/common.go
  examples/lib/tour/06-signing-component-versions/common.go
  examples/lib/tour/docsrc/02-composing-a-component-version/README.md
  pkg/contexts/ocm/add_test.go
  pkg/contexts/ocm/compdesc/componentdescriptor.go
  pkg/contexts/ocm/compdesc/default.go
  pkg/contexts/ocm/compdesc/helper.go
  pkg/contexts/ocm/compdesc/meta/v1/labels.go
  pkg/contexts/ocm/compdesc/util.go
  pkg/contexts/ocm/compdesc/versions/ocm.software/v3alpha1/componentdescriptor.go
  pkg/contexts/ocm/compdesc/versions/v2/componentdescriptor.go
  pkg/contexts/ocm/cpi/dummy.go
  pkg/contexts/ocm/cpi/modopts.go
  pkg/contexts/ocm/cpi/repocpi/view_cv.go
  pkg/contexts/ocm/elements/artifactblob/dirtreeblob/resource_test.go
  pkg/contexts/ocm/elements/artifactblob/helmblob/helmblob_test.go
  pkg/contexts/ocm/elements/artifactblob/mavenblob/access_test.go
  pkg/contexts/ocm/interface.go
  pkg/contexts/ocm/internal/modopts.go
  pkg/contexts/ocm/internal/repository.go
  pkg/contexts/ocm/modopts.go
  pkg/contexts/ocm/signing/handler_test.go
Labels: area/ipcei

#850 Improve errors
  cmds/ocm/commands/common/options/formatoption/option.go
  cmds/ocm/commands/ocmcmds/common/handlers/comphdlr/typehandler.go
  cmds/ocm/commands/ocmcmds/components/download/cmd.go
  cmds/ocm/commands/ocmcmds/pubsub/get/cmd_test.go
  cmds/ocm/commands/ocmcmds/pubsub/set/cmd_test.go
  docs/reference/ocm_add_componentversions.md
  docs/reference/ocm_create_componentarchive.md
  docs/reference/ocm_download_artifacts.md
  docs/reference/ocm_download_componentversions.md
  docs/reference/ocm_ocm-pubsub.md
  docs/reference/ocm_set_pubsub.md
  docs/reference/ocm_transfer_commontransportarchive.md
  docs/reference/ocm_transfer_componentarchive.md
  docs/reference/ocm_transfer_componentversions.md
  pkg/contexts/ocm/pubsub/providers/ocireg/provider_test.go
  pkg/contexts/ocm/pubsub/pubsub_test.go
  pkg/contexts/ocm/pubsub/types/redis/redis_test.go
Labels: area/ipcei, component/ocm-core

#851 add changes for multi-arch
  cmds/ocm/commands/ocmcmds/common/inputs/types/docker/type.go
  cmds/ocm/commands/ocmcmds/common/inputs/types/dockermulti/type.go
  cmds/ocm/commands/ocmcmds/common/inputs/types/ociartifact/type.go
  docs/reference/ocm_add_resource-configuration.md
  docs/reference/ocm_add_resources.md
  docs/reference/ocm_add_source-configuration.md
  docs/reference/ocm_add_sources.md
Labels: size/s

#845 feat: remove GetInexpensiveContentVersionIdentity
  docs/pluginreference/plugin_accessmethod.md
  docs/pluginreference/plugin_accessmethod_identity.md
  pkg/contexts/ocm/accessmethods/compose/method.go
  pkg/contexts/ocm/accessmethods/github/method.go
  pkg/contexts/ocm/accessmethods/helm/method.go
  pkg/contexts/ocm/accessmethods/localblob/method.go
  pkg/contexts/ocm/accessmethods/localblob/method_test.go
  pkg/contexts/ocm/accessmethods/maven/method.go
  pkg/contexts/ocm/accessmethods/maven/method_test.go
  pkg/contexts/ocm/accessmethods/none/method.go
  pkg/contexts/ocm/accessmethods/npm/method.go
  pkg/contexts/ocm/accessmethods/ociartifact/method.go
  pkg/contexts/ocm/accessmethods/ociblob/method.go
  pkg/contexts/ocm/accessmethods/plugin/method.go
  pkg/contexts/ocm/accessmethods/plugin/plugin.go
  pkg/contexts/ocm/accessmethods/relativeociref/method.go
  pkg/contexts/ocm/accessmethods/s3/method.go
  pkg/contexts/ocm/accessmethods/wget/method.go
  pkg/contexts/ocm/cpi/dummy.go
  pkg/contexts/ocm/cpi/repocpi/backend.go
  pkg/contexts/ocm/cpi/repocpi/bridge_cv.go
  pkg/contexts/ocm/cpi/repocpi/view_cv.go
  pkg/contexts/ocm/internal/accessspecref.go
  pkg/contexts/ocm/internal/accesstypes.go
  pkg/contexts/ocm/internal/repository.go
  pkg/contexts/ocm/plugin/descriptor/descriptor.go
  pkg/contexts/ocm/plugin/plugin.go
  pkg/contexts/ocm/plugin/plugin_test.go
  pkg/contexts/ocm/plugin/ppi/cmds/accessmethod/cmd.go
  pkg/contexts/ocm/plugin/ppi/cmds/accessmethod/identity/cmd.go
  pkg/contexts/ocm/plugin/ppi/interface.go
  pkg/contexts/ocm/plugin/ppi/plugin.go
  pkg/contexts/ocm/repositories/comparch/componentarchive.go
  pkg/contexts/ocm/repositories/comparch/repository.go
  pkg/contexts/ocm/repositories/composition/repository.go
  pkg/contexts/ocm/repositories/genericocireg/componentversion.go
  pkg/contexts/ocm/repositories/virtual/access.go
  pkg/contexts/ocm/repositories/virtual/componentversion.go
  pkg/contexts/ocm/repositories/virtual/example/example.go
  pkg/contexts/ocm/repositories/virtual/repo_test.go
  pkg/helm/identity/identity.go
Labels: size/l, area/ipcei, component/ocm-core
