Repository open-component-model/ocm, pull requests merged in 2024-09, with the labels that each got.

#906 align package names with folder names
  api/cli/builder.go
  api/cli/interface.go
  api/oci/types/interface.go
  api/ocm/compdesc/normalizations/init.go
  api/ocm/elements/artifactaccess/ociblobaccess/options.go
  api/ocm/elements/artifactaccess/ociblobaccess/resource.go
  api/ocm/elements/artifactaccess/s3access/options.go
  api/ocm/elements/artifactaccess/s3access/resource.go
  api/ocm/extensions/artifacttypes/const.go
  api/ocm/ocmutils/configure.go
  api/ocm/ocmutils/resource.go
  api/ocm/ocmutils/resourceref.go
  api/ocm/ocmutils/resourceref_test.go
  api/ocm/ocmutils/suite_test.go
  api/ocm/ocmutils/utils.go
  api/ocm/ocmutils/walk.go
  api/ocm/tools/transfer/transferhandler/config/config.go
  api/ocm/types/interface.go
  api/utils/misc/const.go
  api/utils/misc/history.go
  api/utils/misc/history_test.go
  api/utils/misc/printer.go
  api/utils/misc/printer_test.go
  api/utils/misc/properties.go
  api/utils/misc/suite_test.go
  api/utils/misc/types.go
  api/utils/misc/utils.go
  api/utils/misc/walk.go
  cmds/ocm/commands/misccmds/config/cmd.go
  cmds/ocm/commands/misccmds/hash/cmd.go
  cmds/ocm/commands/ocmcmds/common/inputs/types/init.go
Labels: size/s

#907 feedback from migrating a project
  hack/migrate.md
Labels: size/xs

#908 Chore: setup-go@v4 does caching automatically
  .github/workflows/buildcomponents.yaml
  .github/workflows/check_diff_action.yaml
  .github/workflows/components.yaml
  .github/workflows/lint_and_test.yaml
  .github/workflows/push_ocm.yaml
  .github/workflows/release-drafter.yaml
  .github/workflows/release.yaml
Labels: size/m, chore :hammer:

#895 docu: remove some command crosslinks
  cmds/ocm/commands/ocmcmds/components/add/cmd.go
  cmds/ocm/commands/toicmds/config/bootstrap/cmd.go
  cmds/ocm/commands/toicmds/package/bootstrap/cmd.go
  cmds/ocm/commands/toicmds/package/describe/cmd.go
  cmds/ocm/topics/toi/bootstrapping/topic.go
  docs/reference/ocm_add_componentversions.md
  docs/reference/ocm_add_componentversions_ocm-labels.md
  docs/reference/ocm_bootstrap_configuration.md
  docs/reference/ocm_bootstrap_configuration_toi-bootstrapping.md
  docs/reference/ocm_bootstrap_package.md
  docs/reference/ocm_bootstrap_package_toi-bootstrapping.md
  docs/reference/ocm_describe_package.md
  docs/reference/ocm_describe_package_toi-bootstrapping.md
  docs/reference/ocm_toi-bootstrapping.md
Labels: area/documentation, size/l, documentation

#915 feat: remove deprecated functions
  api/ocm/add_test.go
  api/ocm/compdesc/componentdescriptor.go
  api/ocm/compdesc/deprecated.go
  api/ocm/compdesc/helper.go
  api/ocm/compdesc/op.go
  api/ocm/compdesc/selectors.go
  api/ocm/consts/deprecated.go
  api/ocm/cpi/compose_test.go
  api/ocm/cpi/dummy.go
  api/ocm/cpi/modopts.go
  api/ocm/cpi/repocpi/view_cv.go
  api/ocm/cpi/utils.go
  api/ocm/cpi/view_rsc.go
  api/ocm/extensions/repositories/comparch/comparch_test.go
  api/ocm/extensions/repositories/composition/repository_test.go
  api/ocm/extensions/repositories/composition/version_test.go
  api/ocm/internal/repository.go
  api/ocm/ocmutils/resourceref.go
  api/ocm/resolver.go
  api/ocm/resolvers/resolver_test.go
  api/ocm/tools/signing/deprecated.go
  api/ocm/tools/signing/signing_test.go
  api/ocm/tools/signing/transport_test.go
  api/ocm/utils.go
  api/tech/signing/deprecated.go
  api/utils/accessio/cache.go
  api/utils/accessio/deprecated.go
  api/utils/blobaccess/blobaccess/deprecated.go
  api/utils/blobaccess/deprecated.go
  api/utils/blobaccess/dirtree/deprecated.go
  api/utils/blobaccess/dockerdaemon/deprecated.go
  api/utils/blobaccess/dockermulti/deprecated.go
  api/utils/blobaccess/helm/deprecated.go
  api/utils/blobaccess/ociartifact/deprecated.go
  api/utils/blobaccess/wget/deprecated.go
  api/utils/iotools/deprecated.go
  api/utils/selector/selector.go
  cmds/ocm/commands/ocmcmds/resources/download/cmd_test.go
  examples/lib/tour/03-working-with-credentials/02-basic-credential-management.go
  examples/lib/tour/03-working-with-credentials/README.md
Labels: size/l, area/ipcei

#916 Revert "feat: remove deprecated functions"
  api/ocm/add_test.go
  api/ocm/compdesc/componentdescriptor.go
  api/ocm/compdesc/deprecated.go
  api/ocm/compdesc/helper.go
  api/ocm/compdesc/op.go
  api/ocm/compdesc/selectors.go
  api/ocm/consts/deprecated.go
  api/ocm/cpi/compose_test.go
  api/ocm/cpi/dummy.go
  api/ocm/cpi/modopts.go
  api/ocm/cpi/repocpi/view_cv.go
  api/ocm/cpi/utils.go
  api/ocm/cpi/view_rsc.go
  api/ocm/extensions/repositories/comparch/comparch_test.go
  api/ocm/extensions/repositories/composition/repository_test.go
  api/ocm/extensions/repositories/composition/version_test.go
  api/ocm/internal/repository.go
  api/ocm/ocmutils/resourceref.go
  api/ocm/resolver.go
  api/ocm/resolvers/resolver_test.go
  api/ocm/tools/signing/deprecated.go
  api/ocm/tools/signing/signing_test.go
  api/ocm/tools/signing/transport_test.go
  api/ocm/utils.go
  api/tech/signing/deprecated.go
  api/utils/accessio/cache.go
  api/utils/accessio/deprecated.go
  api/utils/blobaccess/blobaccess/deprecated.go
  api/utils/blobaccess/deprecated.go
  api/utils/blobaccess/dirtree/deprecated.go
  api/utils/blobaccess/dockerdaemon/deprecated.go
  api/utils/blobaccess/dockermulti/deprecated.go
  api/utils/blobaccess/helm/deprecated.go
  api/utils/blobaccess/ociartifact/deprecated.go
  api/utils/blobaccess/wget/deprecated.go
  api/utils/iotools/deprecated.go
  api/utils/selector/selector.go
  cmds/ocm/commands/ocmcmds/resources/download/cmd_test.go
  examples/lib/tour/03-working-with-credentials/02-basic-credential-management.go
  examples/lib/tour/03-working-with-credentials/README.md
Labels: size/l

#917 fix: runner caching code that it uses
  .github/workflows/components.yaml
  .github/workflows/lint_and_test.yaml
Labels: size/s, area/ipcei

#919 feat: remove deprecated code - v2
  api/ocm/add_test.go
  api/ocm/compdesc/componentdescriptor.go
  api/ocm/compdesc/deprecated.go
  api/ocm/compdesc/helper.go
  api/ocm/compdesc/helper_test.go
  api/ocm/compdesc/op.go
  api/ocm/compdesc/selectors.go
  api/ocm/consts/deprecated.go
  api/ocm/cpi/compose_test.go
  api/ocm/cpi/dummy.go
  api/ocm/cpi/modopts.go
  api/ocm/cpi/repocpi/view_cv.go
  api/ocm/cpi/utils.go
  api/ocm/cpi/view_rsc.go
  api/ocm/extensions/repositories/comparch/comparch_test.go
  api/ocm/extensions/repositories/composition/repository_test.go
  api/ocm/extensions/repositories/composition/version_test.go
  api/ocm/internal/repository.go
  api/ocm/ocmutils/resourceref.go
  api/ocm/resolver.go
  api/ocm/resolvers/resolver_test.go
  api/ocm/tools/signing/deprecated.go
  api/ocm/tools/signing/signing_test.go
  api/ocm/tools/signing/transport_test.go
  api/ocm/utils.go
  api/tech/signing/deprecated.go
  api/utils/accessio/cache.go
  api/utils/accessio/deprecated.go
  api/utils/blobaccess/blobaccess/deprecated.go
  api/utils/blobaccess/deprecated.go
  api/utils/blobaccess/dirtree/deprecated.go
  api/utils/blobaccess/dockerdaemon/deprecated.go
  api/utils/blobaccess/dockermulti/deprecated.go
  api/utils/blobaccess/helm/deprecated.go
  api/utils/blobaccess/ociartifact/deprecated.go
  api/utils/blobaccess/wget/deprecated.go
  api/utils/iotools/deprecated.go
  api/utils/selector/selector.go
  cmds/ocm/commands/ocmcmds/resources/download/cmd_test.go
  examples/lib/tour/03-working-with-credentials/02-basic-credential-management.go
  examples/lib/tour/03-working-with-credentials/README.md
Labels: size/l, area/ipcei

#920 fix: default component download link
  cmds/ocm/commands/controllercmds/install/cmd.go
  docs/reference/ocm_controller_install.md
Labels: size/xs

#924 Update check_diff_action.yaml
  .github/workflows/check_diff_action.yaml
Labels: size/xs

#923 feat: automatically label all issues with ipcei
  .github/workflows/auto-label-issues.yaml
Labels: size/s, area/ipcei

#928 Documentation: `If the option ...`
  cmds/ocm/commands/ocmcmds/common/options/keepglobaloption/option.go
  cmds/ocm/commands/ocmcmds/common/options/omitaccesstypeoption/option.go
  cmds/ocm/commands/ocmcmds/common/options/overwriteoption/option.go
  cmds/ocm/commands/ocmcmds/common/options/rscbyvalueoption/option.go
  cmds/ocm/commands/ocmcmds/common/options/skipdigestoption/option.go
  cmds/ocm/commands/ocmcmds/common/options/srcbyvalueoption/option.go
  cmds/ocm/commands/ocmcmds/common/options/stoponexistingoption/option.go
  docs/reference/ocm_add_componentversions.md
  docs/reference/ocm_transfer_commontransportarchive.md
  docs/reference/ocm_transfer_componentarchive.md
  docs/reference/ocm_transfer_componentversions.md
Labels: area/documentation, component/documentation, size/s, area/ipcei, documentation

#929 fix busy text file during plugin installation
  api/ocm/extensions/repositories/genericocireg/type.go
  api/ocm/plugin/cache/updater.go
  cmds/ocm/commands/ocmcmds/components/get/cmd_test.go
  cmds/ocm/common/output/treeoutput.go
  cmds/ocm/common/tree/convert.go
  cmds/ocm/common/tree/tree_test.go
  go.mod
  go.sum
Labels: area/ipcei

#930 Add New() to cred-repo dockerconfig provider
  api/credentials/extensions/repositories/dockerconfig/provider.go
Labels: area/ipcei

#933 Update CODEOWNERS
  .github/CODEOWNERS
  CODEOWNERS
Labels: size/s

#931 Release process documentation
  .github/config/wordlist.txt
  README.md
  RELEASE_PROCESS.md
Labels: area/ipcei

#938 fix: some weird maven repositories do return bad index-of listings
  api/tech/maven/access.go
  api/utils/blobaccess/maven/access_test.go
Labels: component/ocm-cli, area/ipcei

#932 feat: add gav matching and overwritable mediatype for file types
  api/ocm/extensions/blobhandler/handlers/generic/maven/blobhandler.go
  api/tech/maven/coordinates.go
  api/utils/blobaccess/maven/access.go
  api/utils/blobaccess/maven/access_test.go
  api/utils/blobaccess/maven/maven.go
  api/utils/blobaccess/maven/options.go
Labels: size/m

#904 feat: replace docker with oras
  .github/config/golangci.yaml
  .github/workflows/lint_and_test.yaml
  Makefile
  api/credentials/utils.go
  api/oci/cpi/support/artifact.go
  api/oci/extensions/repositories/docker/convert.go
  api/oci/extensions/repositories/ocireg/blobs.go
  api/oci/extensions/repositories/ocireg/namespace.go
  api/oci/extensions/repositories/ocireg/repository.go
  api/oci/extensions/repositories/ocireg/utils.go
  api/ocm/cpi/repocpi/bridge_cv.go
  api/ocm/extensions/repositories/genericocireg/componentversion.go
  api/ocm/tools/signing/digest.go
  api/ocm/tools/signing/handle.go
  api/tech/docker/README.md
  api/tech/docker/errors/errors.go
  api/tech/docker/fetcher.go
  api/tech/docker/handler.go
  api/tech/docker/httpreadseeker.go
  api/tech/docker/lister.go
  api/tech/docker/orig.go
  api/tech/docker/pusher.go
  api/tech/docker/registry.go
  api/tech/docker/resolve/interface.go
  api/tech/docker/resolver.go
  api/utils/accessio/cache.go
  api/utils/runtime/scheme.go
  api/utils/spiff/options.go
  api/version/version.go
  cmds/ocm/commands/controllercmds/common/manifests.go
  cmds/ocm/commands/misccmds/rsakeypair/cmd.go
  cmds/ocm/commands/ocmcmds/common/cmds/signing/cmd.go
  cmds/ocm/common/output/complexoutput.go
  cmds/ocm/common/output/table.go
  cmds/ocm/common/processing/buffer.go
  flake.nix
  go.mod
  go.sum
  hack/Makefile
  hack/check.sh
Labels: size/l, area/ipcei

#939 Fix/publish release
  .github/workflows/publish.yaml
  hack/chocolatey/ocm-cli.nuspec
  hack/chocolatey/tools/chocolateyuninstall.ps1
  hack/chocolatey/update.ps1
Labels: size/s

#940 [chore] fix: publish release
  .github/config/wordlist.txt
  .github/workflows/publish.yaml
  examples/lib/contexts.md
  hack/chocolatey/README.md
  hack/chocolatey/tools/chocolateyinstall.ps1
  hack/chocolatey/update.ps1
  hack/winget/README.md
  hack/winget/manifests/o/Open-Component-Model/ocm-cli/0.15.0/Open-Component-Model.ocm-cli.installer.yaml
  hack/winget/manifests/o/Open-Component-Model/ocm-cli/0.15.0/Open-Component-Model.ocm-cli.locale.en-US.yaml
  hack/winget/manifests/o/Open-Component-Model/ocm-cli/0.15.0/Open-Component-Model.ocm-cli.yaml
Labels: size/m, chore :hammer:
