Repository open-component-model/ocm, pull requests merged in 2025-03, with the labels that each got.

#1336 remove PR comment
  .github/workflows/blackduck_scan.yaml
Labels: area/ipcei, kind/chore

#1343 chore!: add bdba trigger to release and exclude subchartsdemo as well as helminstaller / helmdemo from release
  .github/workflows/components.yaml
  .github/workflows/release.yaml
Labels: size/s, area/ipcei, component/github-actions, kind/chore, !BREAKING-CHANGE!

#1356 chore: bump flake.lock to nixpkgs-unstable and clean up flake.nix
  flake.lock
  flake.nix
Labels: size/s, kind/skip-release-notes, kind/chore

#1359 fix: always initialize the system certificate store for the oras client
  api/oci/extensions/repositories/ocireg/repository.go
Labels: kind/bugfix, size/xs

#1367 fix: make sure that other resolve requests such as 400 are also returned as unknown errors so that OCM recognizes them
  api/oci/extensions/repositories/ocireg/namespace.go
Labels: kind/bugfix, size/xs

#1379 fix: downport: make sure that other resolve requests such as 400 are also retur…
  api/oci/extensions/repositories/ocireg/namespace.go
Labels: kind/bugfix, size/xs

#1381 fix: set the refresh token to password always
  api/oci/extensions/repositories/ocireg/repository.go
Labels: kind/bugfix, size/s

#1384 chore: update paths-ignore in lint_and_test workflow to be more specific
  .github/workflows/lint_and_test.yaml
Labels: area/ipcei, component/github-actions, kind/chore

#1386 chore: remove paths-ignore from lint_and_test workflow for pull requests and pushes
  .github/workflows/lint_and_test.yaml
Labels: area/ipcei, component/github-actions, size/xs, kind/chore

#1382 fix: inherit secret for Trigger BDBA Scan
  .github/workflows/lint_and_test.yaml
  .github/workflows/release.yaml
Labels: kind/bugfix, size/s, component/github-actions

#1385 chore: replace Black Duck scan workflow with a trigger workflow
  .github/workflows/blackduck_scan.yaml
  .github/workflows/trigger-blackduck-scan.yaml
Labels: size/s, area/ipcei, component/github-actions, kind/chore

#1387 docs: release on first day of the sprint
  RELEASE_PROCESS.md
Labels: area/documentation, size/xs, kind/chore

#1388 chore: update Black Duck scan workflow reference to specific commit
  .github/workflows/trigger-blackduck-scan.yaml
Labels: area/ipcei, component/github-actions, kind/chore
