Repository open-component-model/ocm, pull requests merged in 2025-06, with the labels that each got.

#1495 fix: correct filename for provenance file (#1492)
  api/ocm/extensions/download/handlers/helm/download_test.go
  api/ocm/extensions/download/handlers/helm/handler.go
  api/ocm/extensions/download/handlers/helm/handler_test.go
Labels: kind/bugfix, size/s, kind/chore

#1496 chore: fix correct filename for provenance file (#1492)
  api/ocm/extensions/download/handlers/helm/download_test.go
  api/ocm/extensions/download/handlers/helm/handler.go
  api/ocm/extensions/download/handlers/helm/handler_test.go
Labels: size/s, kind/chore

#1504 chore!: migrate to native cobra library
  go.mod
  go.sum
Labels: size/xs, kind/dependency, kind/chore, !BREAKING-CHANGE!
