Repository open-component-model/ocm, pull requests merged in 2025-05, with the labels that each got.

#1431 chore: migrate to `golangci-lint/v2`
  .github/config/golangci.yaml
  go.mod
  go.sum
Labels: size/l, component/github-actions, kind/dependency, kind/chore

#1435 chore: switch to stable 24.11
  flake.lock
  flake.nix
Labels: size/s, kind/skip-release-notes, kind/chore

#1437 chore: run `nix flake update`
  .github/workflows/flake_vendorhash.yaml
Labels: component/github-actions, size/xs, kind/chore

#1440 chore: Pin GitHub Actions to commit SHAs
  .github/workflows/check_diff_action.yaml
  .github/workflows/codeql.yml
  .github/workflows/components.yaml
  .github/workflows/flake_vendorhash.yaml
  .github/workflows/lint_and_test.yaml
  .github/workflows/publish-latest.yaml
  .github/workflows/publish-to-other-than-github.yaml
  .github/workflows/pull-request.yaml
  .github/workflows/release-branch.yaml
  .github/workflows/release-bump-version.yaml
  .github/workflows/release-drafter.yaml
  .github/workflows/release-version.yaml
  .github/workflows/release.yaml
  .github/workflows/retrigger-publish-to-other.yaml
  .github/workflows/reuse_helper_tool.yaml
  .github/workflows/verify-md.yml
Labels: size/m, component/github-actions, kind/chore

#1449 chore: GitHub actions add permissions
  .github/workflows/reuse_helper_tool.yaml
  .github/workflows/verify-md.yml
Labels: component/github-actions, size/xs, kind/chore

#1450 chore: sanitize log
  api/utils/logging/roundtripper.go
Labels: size/xs, kind/chore

#1451 chore: adjust GHA permissions
  .github/workflows/publish-to-other-than-github.yaml
  .github/workflows/purge-branch-caches.yaml
Labels: component/github-actions, size/xs, kind/chore

#1454 fix: git access tar methods
  api/utils/blobaccess/git/access.go
  api/utils/blobaccess/git/access_test.go
  api/utils/blobaccess/git/testdata/repo/dir/file_in_dir_in_repo
  api/utils/blobaccess/maven/utils.go
  api/utils/tarutils/pack.go
  api/utils/tarutils/pack_test.go
Labels: kind/bugfix, size/m

#1460 fix(revert): make sure that ref is an option in the gitHub AccessMethod (#1406)
  api/ocm/elements/artifactaccess/githubaccess/resource.go
  api/ocm/extensions/accessmethods/github/README.md
  api/ocm/extensions/accessmethods/github/cli.go
  api/ocm/extensions/accessmethods/github/method.go
  api/ocm/extensions/accessmethods/github/method_test.go
  docs/reference/ocm_add_resource-configuration.md
  docs/reference/ocm_add_resources.md
  docs/reference/ocm_add_source-configuration.md
  docs/reference/ocm_add_sources.md
  docs/reference/ocm_ocm-accessmethods.md
Labels: area/documentation, kind/bugfix, size/m

#1461 fix(revert): make sure that ref is an option in the gitHub AccessMethod (#1406) (#1460)
  api/ocm/elements/artifactaccess/githubaccess/resource.go
  api/ocm/extensions/accessmethods/github/README.md
  api/ocm/extensions/accessmethods/github/cli.go
  api/ocm/extensions/accessmethods/github/method.go
  api/ocm/extensions/accessmethods/github/method_test.go
  docs/reference/ocm_add_resource-configuration.md
  docs/reference/ocm_add_resources.md
  docs/reference/ocm_add_source-configuration.md
  docs/reference/ocm_add_sources.md
  docs/reference/ocm_ocm-accessmethods.md
Labels: area/documentation, kind/bugfix, size/m

#1462 fix(revert): make sure that ref is an option in the gitHub AccessMethod (#1406) (#1460)
  api/ocm/elements/artifactaccess/githubaccess/resource.go
  api/ocm/extensions/accessmethods/github/README.md
  api/ocm/extensions/accessmethods/github/cli.go
  api/ocm/extensions/accessmethods/github/method.go
  api/ocm/extensions/accessmethods/github/method_test.go
  docs/reference/ocm_add_resource-configuration.md
  docs/reference/ocm_add_resources.md
  docs/reference/ocm_add_source-configuration.md
  docs/reference/ocm_add_sources.md
  docs/reference/ocm_ocm-accessmethods.md
Labels: area/documentation, kind/bugfix, size/m

#1471 fix: allow spec compliant, but unusually ordered HELM Chart OCI Artifacts in HELM OCI Artifact downloader (#1470)
  api/ocm/extensions/download/handlers/helm/download_test.go
  api/ocm/extensions/download/handlers/helm/handler.go
  api/ocm/extensions/download/handlers/helm/testdata/unusual-ordered-helm-chart.tgz
Labels: kind/bugfix, size/s

#1472 fix: allow spec compliant, but unusually ordered HELM Chart OCI Artifacts in HELM OCI Artifact downloader (#1470)
  api/ocm/extensions/download/handlers/helm/download_test.go
  api/ocm/extensions/download/handlers/helm/handler.go
  api/ocm/extensions/download/handlers/helm/testdata/unusual-ordered-helm-chart.tgz
Labels: kind/bugfix, size/s

#1473 fix: allow spec compliant, but unusually ordered HELM Chart OCI Artifacts in HELM OCI Artifact downloader (#1470)
  api/ocm/extensions/download/handlers/helm/download_test.go
  api/ocm/extensions/download/handlers/helm/handler.go
  api/ocm/extensions/download/handlers/helm/testdata/unusual-ordered-helm-chart.tgz
Labels: kind/bugfix, size/s

#1478 fix: allow pre-v3.7.0 HELM Charts in HELM OCI Artifact downloader (#1476)
  api/ocm/extensions/download/handlers/helm/download_test.go
  api/ocm/extensions/download/handlers/helm/handler.go
  api/ocm/extensions/download/handlers/helm/testdata/legacy-pre-hip-helm-chart.tgz
Labels: kind/bugfix, size/s

#1479 fix: allow pre-v3.7.0 HELM Charts in HELM OCI Artifact downloader (#1476)
  api/ocm/extensions/download/handlers/helm/download_test.go
  api/ocm/extensions/download/handlers/helm/handler.go
  api/ocm/extensions/download/handlers/helm/testdata/legacy-pre-hip-helm-chart.tgz
Labels: kind/bugfix, size/s

#1481 fix: make sure that helm downloader does not overwrite chart with provenance data
  api/ocm/extensions/download/handlers/helm/download_test.go
  api/ocm/extensions/download/handlers/helm/handler.go
  api/ocm/extensions/download/handlers/helm/handler_test.go
Labels: kind/bugfix, size/m

#1484 fix: make sure that helm downloader does not overwrite chart with provenance data (#1481)
  api/ocm/extensions/download/handlers/helm/download_test.go
  api/ocm/extensions/download/handlers/helm/handler.go
  api/ocm/extensions/download/handlers/helm/handler_test.go
Labels: kind/bugfix, size/m

#1485 fix: make sure that helm downloader does not overwrite chart with provenance data (#1481)
  api/ocm/extensions/download/handlers/helm/download_test.go
  api/ocm/extensions/download/handlers/helm/handler.go
  api/ocm/extensions/download/handlers/helm/handler_test.go
Labels: kind/bugfix, size/m

#1463 chore: remove winget
  .github/config/wordlist.txt
  .github/workflows/publish-to-other-than-github.yaml
  .github/workflows/release.yaml
  .github/workflows/retrigger-publish-to-other.yaml
  README.md
  RELEASE_PROCESS.md
  hack/winget/README.md
Labels: size/s, component/github-actions, kind/chore

#1490 chore: use ternary operator to avoid "skipped" integration test job
  .github/workflows/integration-test.yaml
Labels: size/s, component/github-actions, kind/chore
